// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mshtgwxizxinkxfavnqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zaHRnd3hpenhpbmt4ZmF2bnF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjAwMTksImV4cCI6MjA2NzI5NjAxOX0.WnHMGE85C54NJVYEWtuthhmYOp4qitnjSJKxxfAyZlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});